apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-id
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  # tls:
  # - secretName: ingress-certificate
  #   hosts:
  #   - localhost
  rules:
  - host: restaurante
    http:
      paths:
      - path: /app-id(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: app-id
            port:
              number: 80